# Generated by Django 4.0.5 on 2022-07-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppost', '0002_remove_creator_name_post_name_alter_post_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
