# Generated by Django 4.0.5 on 2022-07-18 01:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppost', '0004_rename_content_post_contex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contex',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
